### ISSUE TITLE
这个mod上创意工坊了吗? 直接搜名字没搜到

### ISSUE THREAD

**Issue by textGamex** [Supheria/The_Road_to_Touhou#1]

**Comment by Supheria** [comment]
> _No description provided._
没有呢，搁置了一年多了，因为我自己没有成功把可视化模组编辑器弄出来。

虽然可以不用开发可视化编辑器直接开发模组，但是我总觉得这会欠下很多技术债，导致此mod后续难以维护和持续开发，所以我的重点一直在开发模组编辑器上，导致模组的开发过程中遇到很多麻烦和转折。

例如，在UI部分用的是Winform，但是陆陆续续优化直到现在还是会因为Winform的GDI太过时导致性能问题，直到最近才开始转向Avalonia，因为它使用xaml并支跨平台。

如果后续能把可视化模组编辑器能做出来这个mod会继续做下去，因为策划和美工的很多素材都已经准备好了。
